// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Custom API Routes
 *
 * This file is the editable surface for custom backend logic that
 * doesn't fit the auto-generated CRUD model (per-model GET/POST/PATCH/
 * DELETE under `/api/<model>s`). Anything you mount on the exported
 * Hono app shows up at `/api/...` alongside the generated CRUD routes.
 *
 * Examples:
 *   - Aggregations / dashboards: `app.get('/dashboard', ...)`
 *   - Webhooks: `app.post('/webhooks/stripe', ...)`
 *   - Auth flows: `app.post('/auth/login', ...)`
 *
 * For installed integrations (Jira, Slack, Google, Meta Ads, etc.):
 *
 * - Dashboards / list views / "my X" pages → mount a route HERE that
 *   uses `getServerToolsClient()`. Resolve identity per request with
 *   `<TOOLKIT>_GET_CURRENT_USER`, compose the calls you need, return
 *   a clean shape your component owns.
 *
 *   The SDK auto-parses tool result `data` on success (the runtime
 *   JSON.stringifies tool responses; @shogo-ai/sdk/tools >=1.3 parses
 *   them back). Index `data` like a plain object — do NOT write a
 *   `JSON.parse(result.data)` helper. Pass a generic to `execute<T>()`
 *   for typed access.
 *
 *   import { getServerToolsClient } from '@shogo-ai/sdk/tools'
 *
 *   app.get('/jira/my-issues', async (c) => {
 *     const tools = getServerToolsClient()
 *     const me = await tools.execute<{ accountId: string }>('JIRA_GET_CURRENT_USER', {})
 *     if (!me.ok || !me.data?.accountId) {
 *       return c.json({ error: me.error ?? 'not authenticated' }, 401)
 *     }
 *     const issues = await tools.execute<{ issues: unknown[] }>('JIRA_SEARCH_ISSUES', {
 *       jql: `assignee = "${me.data.accountId}"`,
 *     })
 *     if (!issues.ok) return c.json({ error: issues.error ?? 'search failed' }, 502)
 *     return c.json({ issues: issues.data?.issues ?? [] })
 *   })
 *
 *   In the browser, surface the server's `error` field — never throw
 *   `new Error('Failed to load X')`:
 *
 *     const res = await fetch('/api/jira/my-issues')
 *     const body = await res.json().catch(() => ({}))
 *     if (!res.ok) setError(body.error ?? `HTTP ${res.status}`)
 *     else setIssues(body.issues ?? [])
 *
 *   After writing or editing a route, hit it to confirm shape + status:
 *     curl -s -w "\nHTTP %{http_code}\n" http://localhost:$RUNTIME_PORT/api/jira/my-issues
 *   A green build proves the file compiled, not that the endpoint works.
 *
 * - Ad-hoc interactive actions (button clicks, form submits) → use
 *   `useTools()` directly in the component. Don't add a route here for
 *   single-call passthroughs.
 *
 * Hand-rolling a `fetch()` to the provider's REST API will fail
 * because the pod has no provider tokens — auth lives in the runtime.
 * NEVER hardcode the agent operator's identity (accountId, member id,
 * userId) into route code; resolve it per request as shown above.
 *
 * The runtime watches this file. Saving triggers a fast restart of
 * `server.tsx` (no schema regeneration, no `prisma db push`) so changes
 * land in under a second.
 *
 * The Prisma client is available — import it from `./src/lib/db`:
 *
 *   import { prisma } from './src/lib/db'
 *
 *   app.get('/stats', async (c) => {
 *     const userCount = await prisma.user.count()
 *     return c.json({ userCount })
 *   })
 *
 * Do NOT edit `server.tsx` — it is auto-generated by the SDK from
 * `shogo.config.json` and will be overwritten on the next regeneration.
 */

import { Hono } from 'hono'
import { prisma } from './src/lib/db'

const app = new Hono()

const SELLER_WALLET = '1QLTRW2YLBcwWJbCb1imGgwp98cSrUhNGJ'
const DEFAULT_COMMISSION_RATE = 0.05

// --- Seed games on first call ---
let gamesSeeded = false

async function seedGames() {
  if (gamesSeeded) return
  const count = await prisma.game.count()
  if (count > 0) { gamesSeeded = true; return }

  const games = [
    { title: 'Crypto Legends', description: 'Battle other players in this crypto-themed MOBA. Earn Bitcoin for every victory!', genre: 'MOBA', price: 0.005, rating: 4.8, players: 125000, featured: true },
    { title: 'Neon Racing', description: 'High-speed cyberpunk racing with crypto rewards. Customize your ride with NFT parts!', genre: 'Racing', price: 0.003, rating: 4.6, players: 89000, isNew: true },
    { title: 'Phantom Protocol', description: 'Stealth action game set in a dystopian future. Hack, infiltrate, and survive.', genre: 'Action', price: 0.008, rating: 4.9, players: 203000, featured: true },
    { title: 'Pixel Warriors', description: 'Retro-style RPG with modern blockchain rewards. Level up and earn BTC!', genre: 'RPG', price: 0.002, rating: 4.5, players: 67000 },
    { title: 'Target Strike', description: 'Tactical FPS with crypto tournaments. Compete for weekly Bitcoin prizes.', genre: 'FPS', price: 0.004, rating: 4.7, players: 156000 },
    { title: 'Shield Defense', description: 'Tower defense with blockchain integration. Protect your crypto fortress!', genre: 'Strategy', price: 0.001, rating: 4.4, players: 45000, isNew: true },
  ]

  await prisma.game.createMany({ data: games })
  gamesSeeded = true
}

// --- Get all games ---
app.get('/games', async (c) => {
  await seedGames()
  const games = await prisma.game.findMany({ orderBy: { createdAt: 'desc' } })
  return c.json({ games })
})

// --- Process a purchase (player buys a game) ---
app.post('/payments/purchase', async (c) => {
  const body = await c.req.json()
  const { gameId, buyerAddress, txHash } = body

  if (!gameId || !buyerAddress) {
    return c.json({ error: 'gameId and buyerAddress are required' }, 400)
  }

  const game = await prisma.game.findUnique({ where: { id: gameId } })
  if (!game) return c.json({ error: 'Game not found' }, 404)

  const commissionRate = DEFAULT_COMMISSION_RATE
  const commissionAmount = +(game.price * commissionRate).toFixed(8)
  const sellerAmount = +(game.price - commissionAmount).toFixed(8)

  const purchase = await prisma.gamePurchase.create({
    data: {
      gameId,
      buyerAddress,
      sellerAddress: SELLER_WALLET,
      amount: game.price,
      commissionRate,
      commissionAmount,
      sellerAmount,
      txHash: txHash || null,
      status: txHash ? 'pending' : 'awaiting_payment',
    },
  })

  // Record commission ledger entry for the seller
  await prisma.commissionLedger.create({
    data: {
      purchaseId: purchase.id,
      sellerAddress: SELLER_WALLET,
      amount: commissionAmount,
      txHash: txHash || null,
      status: 'pending',
    },
  })

  return c.json({
    purchase: {
      id: purchase.id,
      game: game.title,
      totalAmount: game.price,
      commissionRate: `${(commissionRate * 100).toFixed(0)}%`,
      commissionAmount,
      sellerAmount,
      yourEarnings: commissionAmount,
      status: purchase.status,
      txHash: purchase.txHash,
    },
    message: `Commission of ${commissionAmount} BTC recorded for seller. You earn ${commissionAmount} BTC from this ${game.price} BTC sale.`,
  })
})

// --- Verify a transaction hash and auto-confirm ---
app.post('/payments/verify', async (c) => {
  const body = await c.req.json()
  const { txHash } = body

  if (!txHash) return c.json({ error: 'txHash is required' }, 400)

  const purchase = await prisma.gamePurchase.findFirst({ where: { txHash } })
  if (!purchase) return c.json({ error: 'Transaction not found in our system' }, 404)

  // Simulate blockchain verification (in production, call a Bitcoin node or API)
  const confirmations = Math.floor(Math.random() * 10) + 1
  const status = confirmations >= 6 ? 'confirmed' : 'pending'

  const updated = await prisma.gamePurchase.update({
    where: { id: purchase.id },
    data: {
      confirmations,
      status,
      confirmedAt: status === 'confirmed' ? new Date() : null,
    },
  })

  // Update commission ledger if confirmed
  if (status === 'confirmed') {
    await prisma.commissionLedger.updateMany({
      where: { purchaseId: purchase.id },
      data: { status: 'confirmed', txHash },
    })
  }

  return c.json({
    txHash,
    confirmations,
    status,
    amount: purchase.amount,
    commissionEarned: purchase.commissionAmount,
    message: status === 'confirmed'
      ? `Transaction confirmed! ${purchase.commissionAmount} BTC commission credited.`
      : `Transaction pending — ${confirmations}/6 confirmations.`,
  })
})

// --- Earnings dashboard (owner's view) ---
app.get('/earnings/dashboard', async (c) => {
  await seedGames()

  const allPurchases = await prisma.gamePurchase.findMany({
    include: { game: true },
    orderBy: { createdAt: 'desc' },
  })

  const allLedger = await prisma.commissionLedger.findMany({
    orderBy: { createdAt: 'desc' },
  })

  const totalRevenue = allPurchases.reduce((sum, p) => sum + p.amount, 0)
  const totalCommission = allLedger.reduce((sum, l) => sum + l.amount, 0)
  const confirmedCommission = allLedger
    .filter((l) => l.status === 'confirmed')
    .reduce((sum, l) => sum + l.amount, 0)
  const pendingCommission = allLedger
    .filter((l) => l.status === 'pending')
    .reduce((sum, l) => sum + l.amount, 0)
  const totalSales = allPurchases.length
  const confirmedSales = allPurchases.filter((p) => p.status === 'confirmed').length
  const pendingSales = allPurchases.filter((p) => p.status === 'pending' || p.status === 'awaiting_payment').length

  // Earnings by game
  const gameStats: Record<string, { sales: number; revenue: number; commission: number }> = {}
  for (const p of allPurchases) {
    const title = p.game.title
    if (!gameStats[title]) gameStats[title] = { sales: 0, revenue: 0, commission: 0 }
    gameStats[title].sales++
    gameStats[title].revenue += p.amount
    gameStats[title].commission += p.commissionAmount
  }

  // Recent transactions (last 20)
  const recentTransactions = allPurchases.slice(0, 20).map((p) => ({
    id: p.id,
    game: p.game.title,
    buyerAddress: p.buyerAddress,
    totalAmount: p.amount,
    commissionEarned: p.commissionAmount,
    status: p.status,
    confirmations: p.confirmations,
    txHash: p.txHash,
    createdAt: p.createdAt,
    confirmedAt: p.confirmedAt,
  }))

  return c.json({
    wallet: SELLER_WALLET,
    commissionRate: `${(DEFAULT_COMMISSION_RATE * 100).toFixed(0)}%`,
    summary: {
      totalRevenue: +totalRevenue.toFixed(8),
      totalCommission: +totalCommission.toFixed(8),
      confirmedCommission: +confirmedCommission.toFixed(8),
      pendingCommission: +pendingCommission.toFixed(8),
      totalSales,
      confirmedSales,
      pendingSales,
    },
    gameStats: Object.entries(gameStats).map(([title, stats]) => ({
      title,
      ...stats,
      commission: +stats.commission.toFixed(8),
      revenue: +stats.revenue.toFixed(8),
    })),
    recentTransactions,
  })
})

// --- Get purchase details by txHash ---
app.get('/payments/:txHash', async (c) => {
  const txHash = c.req.param('txHash')
  const purchase = await prisma.gamePurchase.findFirst({
    where: { txHash },
    include: { game: true },
  })
  if (!purchase) return c.json({ error: 'Transaction not found' }, 404)
  return c.json({
    id: purchase.id,
    game: purchase.game.title,
    buyerAddress: purchase.buyerAddress,
    sellerAddress: purchase.sellerAddress,
    totalAmount: purchase.amount,
    commissionRate: purchase.commissionRate,
    commissionAmount: purchase.commissionAmount,
    sellerAmount: purchase.sellerAmount,
    status: purchase.status,
    confirmations: purchase.confirmations,
    txHash: purchase.txHash,
    createdAt: purchase.createdAt,
    confirmedAt: purchase.confirmedAt,
  })
})

// --- Simulate incoming player payments (demo/testing) ---
app.post('/payments/simulate', async (c) => {
  await seedGames()
  const games = await prisma.game.findMany()

  const buyerWallets = [
    '1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa',
    '3J98t1WpEZ73CNmQviecrnyiWrnqRhWNLy',
    'bc1qar0srrr7xfkvy5l643lydnw9re59gtzzwf5mdq',
    '1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2',
    '1CounterpartyXXXXXXXXXXXXXXXUWLpVr',
    '1Lbcfr7sAHTD9CgdQo3HTMTkV8LK4ZnX71',
    '1XPTgDRhN8RFnzniWCddobD9iKZatrvH4',
    '15ubicBBWFnvoZLT7GiU2qxjRaKRNqSMvR',
  ]

  const statuses = ['confirmed', 'pending', 'confirmed', 'confirmed', 'pending']
  const created = []

  for (let i = 0; i < 5; i++) {
    const game = games[Math.floor(Math.random() * games.length)]
    const buyer = buyerWallets[Math.floor(Math.random() * buyerWallets.length)]
    const commissionRate = DEFAULT_COMMISSION_RATE
    const commissionAmount = +(game.price * commissionRate).toFixed(8)
    const sellerAmount = +(game.price - commissionAmount).toFixed(8)
    const status = statuses[i]
    const confirmations = status === 'confirmed' ? Math.floor(Math.random() * 10) + 6 : Math.floor(Math.random() * 5)
    const txHash = Array.from({ length: 64 }, () => '0123456789abcdef'[Math.floor(Math.random() * 16)]).join('')

    const purchase = await prisma.gamePurchase.create({
      data: {
        gameId: game.id,
        buyerAddress: buyer,
        sellerAddress: SELLER_WALLET,
        amount: game.price,
        commissionRate,
        commissionAmount,
        sellerAmount,
        txHash,
        status,
        confirmations,
        confirmedAt: status === 'confirmed' ? new Date() : null,
      },
    })

    await prisma.commissionLedger.create({
      data: {
        purchaseId: purchase.id,
        sellerAddress: SELLER_WALLET,
        amount: commissionAmount,
        txHash,
        status,
      },
    })

    created.push({
      game: game.title,
      buyer,
      amount: game.price,
      commission: commissionAmount,
      status,
      txHash,
    })
  }

  return c.json({
    message: `Simulated ${created.length} player purchases. Your commission earnings updated!`,
    transactions: created,
  })
})

export default app
