// Auto-generated by agent-runtime — do not edit.
// Adds .shogo/ to Vite's watch ignore to prevent build-log infinite loops.
import { defineConfig, mergeConfig } from 'vite'
import userConfig from '../vite.config'

export default mergeConfig(userConfig, defineConfig({
  server: {
    watch: {
      ignored: ['**/.shogo/**'],
    },
  },
}))
